#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check Prettier standards
npm run check-format ||
(
    echo '❌ Prettier Check Failed. Run `npm run format`, add changes and try commit again.';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo '❌ ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

echo '✅ Project looks fresh, committing...'
